// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkadgnpyjzuqqixrdbiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrYWRnbnB5anp1cXFpeHJkYml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzY2MDYsImV4cCI6MjA2MzI1MjYwNn0.vOqbx070vpHOjW95S2zHxSNTbfI-m3DYtcdFCXLPfhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);